# Make sure to set up GENIE before building
ROOT_CXX_FLAGS := $(shell root-config --cflags) -fPIC
ROOT_LIBS := $(shell root-config --libs --evelibs) -lMathMore

GENIE_CXX_FLAGS := -I$(shell genie-config --topsrcdir) -I${LOG4CPP_INC}
GENIE_LIBS := $(shell genie-config --libs) -L${LOG4CPP_LIB} -lxml2 -llog4cpp
GENIE_LIBS += -lEGPythia6 $(gsl-config --libs) -lGenVector
GENIE_LIBS += -L${LHAPDF_LIB} -lLHAPDF

# When including the Fortran code, you will likely need to link the executable
# to -lgfortran as well
test_xsec: test_xsec.o FortranWrapperQELPXSec.o FortranWrapperEventGenerator.o FortranWrapperXSecIntegrator.o root_dictionary.o currents_opt_v1.o xsec_fact_new.o diracmatrices.o \
  nform.o
	$(CXX) $(ROOT_LIBS) $(GENIE_LIBS) -o $@ $^ -lgfortran

%.o: %.cxx
	$(CXX) $(ROOT_CXX_FLAGS) $(GENIE_CXX_FLAGS) -o $@ -c $^

%.o: %.f90
	gfortran -o $@ -c $^

root_dictionary.o:
	$(RM) root_dictionary*.*
	rootcling -f root_dictionary.cxx $(GENIE_CXX_FLAGS) \
	  -c FortranWrapperQELPXSec.h LinkDef.h
	$(CXX) $(ROOT_CXX_FLAGS) $(GENIE_CXX_FLAGS) \
	-o $@ -c root_dictionary.cxx
	$(RM) root_dictionary.cxx

.PHONY: clean

clean:
	$(RM) *.o test_xsec root_dictionary_rdict.pcm
